"""add_panel_nodegraph_models

Revision ID: 2c90706fe739
Revises: 2a19e6b76e6f
Create Date: 2026-04-19 18:53:09.047608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c90706fe739'
down_revision: Union[str, Sequence[str], None] = '2a19e6b76e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id')
    )
    op.create_table('graph_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.String(length=32), nullable=False),
    sa.Column('source_output', sa.String(length=64), nullable=False),
    sa.Column('target_node_id', sa.String(length=32), nullable=False),
    sa.Column('target_input', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['node_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['node_graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_nodes')
    op.drop_table('graph_connections')
    op.drop_table('node_graphs')
    op.drop_table('panels')
    # ### end Alembic commands ###
