"""add_panel_collapsed

Revision ID: 53b61700e60d
Revises: 4e0e90030bd4
Create Date: 2026-04-22 14:19:40.325499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '53b61700e60d'
down_revision: Union[str, Sequence[str], None] = '4e0e90030bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('collapsed', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'collapsed')
    # ### end Alembic commands ###
