"""migrate device to multi-endpoint firmware v1.0.0

Revision ID: d0011bc29292
Revises: dafec90e94da
Create Date: 2026-04-18 14:58:16.891937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0011bc29292'
down_revision: Union[str, Sequence[str], None] = 'dafec90e94da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoints', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.JSON(), nullable=True))
        batch_op.drop_column('supports_hs')
        batch_op.drop_column('endpoint')
        batch_op.drop_column('supports_ct')
        batch_op.drop_column('supports_xy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supports_xy', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('supports_ct', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('endpoint', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('supports_hs', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('state')
        batch_op.drop_column('endpoints')
    # ### end Alembic commands ###
