"""add device last_command

Revision ID: 0ae4f6328ad0
Revises: 6d15cf0ee0f1
Create Date: 2026-04-18 00:32:47.278873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae4f6328ad0'
down_revision: Union[str, Sequence[str], None] = '6d15cf0ee0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_command', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_command')
    # ### end Alembic commands ###
