"""add devices table

Revision ID: 6d15cf0ee0f1
Revises: aaa5a4060395
Create Date: 2026-04-17 23:21:51.944443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d15cf0ee0f1'
down_revision: Union[str, Sequence[str], None] = 'aaa5a4060395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('ieee_addr', sa.String(length=32), nullable=False),
    sa.Column('network_addr', sa.String(length=8), nullable=True),
    sa.Column('endpoint', sa.Integer(), nullable=True),
    sa.Column('supports_hs', sa.Boolean(), nullable=False),
    sa.Column('supports_xy', sa.Boolean(), nullable=False),
    sa.Column('supports_ct', sa.Boolean(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ieee_addr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
